// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * ArtifactData
 */
export type ArtifactData = {
    /**
     * Total Size
     */
    total_size: number;
    /**
     * Is Dir
     */
    is_dir: boolean;
    /**
     * Hash
     */
    hash: string;
    /**
     * Uri
     */
    uri?: string | null;
    /**
     * Value
     */
    value?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Deleted At
     */
    deleted_at?: string | null;
    /**
     * Extra Data
     */
    extra_data?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ArtifactDataResponse
 */
export type ArtifactDataResponse = {
    /**
     * Total Size
     */
    total_size: number;
    /**
     * Is Dir
     */
    is_dir: boolean;
    /**
     * Uri
     */
    uri?: string | null;
    /**
     * Value
     */
    value?: string | null;
};

/**
 * ArtifactNodeIdResponse
 */
export type ArtifactNodeIdResponse = {
    /**
     * Id
     */
    id: string;
};

/**
 * ArtifactNodeResponse
 */
export type ArtifactNodeResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Type Name
     */
    type_name?: string | null;
    /**
     * Type Properties
     */
    type_properties?: {
        [key: string]: unknown;
    } | null;
    /**
     * Producer Execution Id
     */
    producer_execution_id?: string | null;
    /**
     * Producer Output Name
     */
    producer_output_name?: string | null;
    artifact_data?: ArtifactDataResponse | null;
};

/**
 * Body_create_api_pipeline_runs__post
 */
export type BodyCreateApiPipelineRunsPost = {
    root_task: TaskSpecInput;
    /**
     * Components
     */
    components?: Array<ComponentReferenceInput> | null;
    /**
     * Annotations
     */
    annotations?: {
        [key: string]: unknown;
    } | null;
};

/**
 * Body_create_secret_api_secrets__post
 */
export type BodyCreateSecretApiSecretsPost = {
    /**
     * Secret Value
     */
    secret_value: string;
};

/**
 * Body_set_settings_api_users_me_settings_patch
 */
export type BodySetSettingsApiUsersMeSettingsPatch = {
    /**
     * Settings
     */
    settings: {
        [key: string]: unknown;
    };
};

/**
 * Body_update_secret_api_secrets__secret_name__put
 */
export type BodyUpdateSecretApiSecretsSecretNamePut = {
    /**
     * Secret Value
     */
    secret_value: string;
};

/**
 * CachingStrategySpec
 */
export type CachingStrategySpec = {
    /**
     * Maxcachestaleness
     */
    maxCacheStaleness?: string | null;
};

/**
 * ComponentLibrary
 */
export type ComponentLibrary = {
    /**
     * Name
     */
    name: string;
    root_folder: ComponentLibraryFolderInput;
    /**
     * Annotations
     */
    annotations?: {
        [key: string]: string;
    } | null;
};

/**
 * ComponentLibraryFolder
 */
export type ComponentLibraryFolderInput = {
    /**
     * Name
     */
    name: string;
    /**
     * Folders
     */
    folders?: Array<ComponentLibraryFolderInput> | null;
    /**
     * Components
     */
    components?: Array<ComponentReferenceInput> | null;
    /**
     * Annotations
     */
    annotations?: {
        [key: string]: string;
    } | null;
};

/**
 * ComponentLibraryFolder
 */
export type ComponentLibraryFolderOutput = {
    /**
     * Name
     */
    name: string;
    /**
     * Folders
     */
    folders?: Array<ComponentLibraryFolderOutput> | null;
    /**
     * Components
     */
    components?: Array<ComponentReferenceOutput> | null;
    /**
     * Annotations
     */
    annotations?: {
        [key: string]: string;
    } | null;
};

/**
 * ComponentLibraryResponse
 */
export type ComponentLibraryResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    root_folder?: ComponentLibraryFolderOutput | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Published By
     */
    published_by?: string | null;
    /**
     * Hide From Search
     */
    hide_from_search?: boolean;
    /**
     * Annotations
     */
    annotations?: {
        [key: string]: string;
    } | null;
    /**
     * Component Count
     */
    component_count?: number;
};

/**
 * ComponentReference
 */
export type ComponentReferenceInput = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Digest
     */
    digest?: string | null;
    /**
     * Tag
     */
    tag?: string | null;
    /**
     * Url
     */
    url?: string | null;
    spec?: ComponentSpecInput | null;
    /**
     * Text
     */
    text?: string | null;
};

/**
 * ComponentReference
 */
export type ComponentReferenceOutput = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Digest
     */
    digest?: string | null;
    /**
     * Tag
     */
    tag?: string | null;
    /**
     * Url
     */
    url?: string | null;
    spec?: ComponentSpecOutput | null;
    /**
     * Text
     */
    text?: string | null;
};

/**
 * ComponentResponse
 */
export type ComponentResponse = {
    /**
     * Digest
     */
    digest: string;
    /**
     * Text
     */
    text: string;
};

/**
 * ComponentSpec
 */
export type ComponentSpecInput = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    metadata?: MetadataSpec | null;
    /**
     * Inputs
     */
    inputs?: Array<InputSpec> | null;
    /**
     * Outputs
     */
    outputs?: Array<OutputSpec> | null;
    /**
     * Implementation
     */
    implementation?: ContainerImplementationInput | GraphImplementationInput | null;
};

/**
 * ComponentSpec
 */
export type ComponentSpecOutput = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    metadata?: MetadataSpec | null;
    /**
     * Inputs
     */
    inputs?: Array<InputSpec> | null;
    /**
     * Outputs
     */
    outputs?: Array<OutputSpec> | null;
    /**
     * Implementation
     */
    implementation?: ContainerImplementationOutput | GraphImplementationOutput | null;
};

/**
 * ConcatPlaceholder
 */
export type ConcatPlaceholderInput = {
    /**
     * Concat
     */
    concat: Array<string | InputValuePlaceholder | InputPathPlaceholder | OutputPathPlaceholder | ConcatPlaceholderInput | IfPlaceholderInput>;
};

/**
 * ConcatPlaceholder
 */
export type ConcatPlaceholderOutput = {
    /**
     * Concat
     */
    concat: Array<string | InputValuePlaceholder | InputPathPlaceholder | OutputPathPlaceholder | ConcatPlaceholderOutput | IfPlaceholderOutput>;
};

/**
 * ContainerExecutionStatus
 */
export type ContainerExecutionStatus = 'INVALID' | 'UNINITIALIZED' | 'QUEUED' | 'WAITING_FOR_UPSTREAM' | 'PENDING' | 'RUNNING' | 'SUCCEEDED' | 'FAILED' | 'SYSTEM_ERROR' | 'CANCELLING' | 'CANCELLED' | 'SKIPPED';

/**
 * ContainerImplementation
 */
export type ContainerImplementationInput = {
    container: ContainerSpecInput;
};

/**
 * ContainerImplementation
 */
export type ContainerImplementationOutput = {
    container: ContainerSpecOutput;
};

/**
 * ContainerSpec
 */
export type ContainerSpecInput = {
    /**
     * Image
     */
    image: string;
    /**
     * Command
     */
    command?: Array<string | InputValuePlaceholder | InputPathPlaceholder | OutputPathPlaceholder | ConcatPlaceholderInput | IfPlaceholderInput> | null;
    /**
     * Args
     */
    args?: Array<string | InputValuePlaceholder | InputPathPlaceholder | OutputPathPlaceholder | ConcatPlaceholderInput | IfPlaceholderInput> | null;
    /**
     * Env
     */
    env?: {
        [key: string]: string;
    } | null;
};

/**
 * ContainerSpec
 */
export type ContainerSpecOutput = {
    /**
     * Image
     */
    image: string;
    /**
     * Command
     */
    command?: Array<string | InputValuePlaceholder | InputPathPlaceholder | OutputPathPlaceholder | ConcatPlaceholderOutput | IfPlaceholderOutput> | null;
    /**
     * Args
     */
    args?: Array<string | InputValuePlaceholder | InputPathPlaceholder | OutputPathPlaceholder | ConcatPlaceholderOutput | IfPlaceholderOutput> | null;
    /**
     * Env
     */
    env?: {
        [key: string]: string;
    } | null;
};

/**
 * DynamicDataArgument
 */
export type DynamicDataArgument = {
    /**
     * Dynamicdata
     */
    dynamicData: string | {
        [key: string]: unknown;
    };
};

/**
 * ExecutionNodeReference
 */
export type ExecutionNodeReference = {
    /**
     * Execution Node Id
     */
    execution_node_id: string;
    /**
     * Pipeline Run Id
     */
    pipeline_run_id: string | null;
};

/**
 * ExecutionOptionsSpec
 */
export type ExecutionOptionsSpec = {
    retryStrategy?: RetryStrategySpec | null;
    cachingStrategy?: CachingStrategySpec | null;
};

/**
 * ExecutionStatusSummary
 */
export type ExecutionStatusSummary = {
    /**
     * Total Executions
     */
    total_executions: number;
    /**
     * Ended Executions
     */
    ended_executions: number;
    /**
     * Has Ended
     */
    has_ended: boolean;
};

/**
 * GetArtifactInfoResponse
 */
export type GetArtifactInfoResponse = {
    /**
     * Id
     */
    id: string;
    artifact_data?: ArtifactData | null;
};

/**
 * GetArtifactSignedUrlResponse
 */
export type GetArtifactSignedUrlResponse = {
    /**
     * Signed Url
     */
    signed_url: string;
};

/**
 * GetContainerExecutionLogResponse
 */
export type GetContainerExecutionLogResponse = {
    /**
     * Log Text
     */
    log_text?: string | null;
    /**
     * System Error Exception Full
     */
    system_error_exception_full?: string | null;
    /**
     * Orchestration Error Message
     */
    orchestration_error_message?: string | null;
};

/**
 * GetContainerExecutionStateResponse
 */
export type GetContainerExecutionStateResponse = {
    status: ContainerExecutionStatus;
    /**
     * Exit Code
     */
    exit_code?: number | null;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Ended At
     */
    ended_at?: string | null;
    /**
     * Debug Info
     */
    debug_info?: {
        [key: string]: unknown;
    } | null;
    /**
     * Execution Nodes Linked To Same Container Execution
     */
    execution_nodes_linked_to_same_container_execution?: Array<ExecutionNodeReference> | null;
};

/**
 * GetExecutionArtifactsResponse
 */
export type GetExecutionArtifactsResponse = {
    /**
     * Input Artifacts
     */
    input_artifacts?: {
        [key: string]: ArtifactNodeResponse;
    } | null;
    /**
     * Output Artifacts
     */
    output_artifacts?: {
        [key: string]: ArtifactNodeResponse;
    } | null;
};

/**
 * GetExecutionInfoResponse
 */
export type GetExecutionInfoResponse = {
    /**
     * Id
     */
    id: string;
    task_spec: TaskSpecOutput;
    /**
     * Parent Execution Id
     */
    parent_execution_id?: string | null;
    /**
     * Child Task Execution Ids
     */
    child_task_execution_ids: {
        [key: string]: string;
    };
    /**
     * Pipeline Run Id
     */
    pipeline_run_id?: string | null;
    /**
     * Input Artifacts
     */
    input_artifacts?: {
        [key: string]: ArtifactNodeIdResponse;
    } | null;
    /**
     * Output Artifacts
     */
    output_artifacts?: {
        [key: string]: ArtifactNodeIdResponse;
    } | null;
};

/**
 * GetGraphExecutionStateResponse
 */
export type GetGraphExecutionStateResponse = {
    /**
     * Child Execution Status Stats
     */
    child_execution_status_stats: {
        [key: string]: {
            [key: string]: number;
        };
    };
    child_execution_status_summary: ExecutionStatusSummary;
};

/**
 * GetUserResponse
 */
export type GetUserResponse = {
    /**
     * Id
     */
    id: string | null;
    /**
     * Permissions
     */
    permissions: Array<string>;
};

/**
 * GraphImplementation
 */
export type GraphImplementationInput = {
    graph: GraphSpecInput;
};

/**
 * GraphImplementation
 */
export type GraphImplementationOutput = {
    graph: GraphSpecOutput;
};

/**
 * GraphInputArgument
 */
export type GraphInputArgument = {
    graphInput: GraphInputReference;
};

/**
 * GraphInputReference
 */
export type GraphInputReference = {
    /**
     * Inputname
     */
    inputName: string;
    /**
     * Type
     */
    type?: string | {
        [key: string]: unknown;
    } | Array<unknown> | null;
};

/**
 * GraphSpec
 */
export type GraphSpecInput = {
    /**
     * Tasks
     */
    tasks: {
        [key: string]: TaskSpecInput;
    };
    /**
     * Outputvalues
     */
    outputValues?: {
        [key: string]: string | GraphInputArgument | TaskOutputArgument | DynamicDataArgument;
    } | null;
};

/**
 * GraphSpec
 */
export type GraphSpecOutput = {
    /**
     * Tasks
     */
    tasks: {
        [key: string]: TaskSpecOutput;
    };
    /**
     * Outputvalues
     */
    outputValues?: {
        [key: string]: string | GraphInputArgument | TaskOutputArgument | DynamicDataArgument;
    } | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IfPlaceholder
 */
export type IfPlaceholderInput = {
    if: IfPlaceholderStructureInput;
};

/**
 * IfPlaceholder
 */
export type IfPlaceholderOutput = {
    if: IfPlaceholderStructureOutput;
};

/**
 * IfPlaceholderStructure
 */
export type IfPlaceholderStructureInput = {
    /**
     * Cond
     */
    cond: boolean | string | IsPresentPlaceholder | InputValuePlaceholder;
    /**
     * Then
     */
    then: Array<string | InputValuePlaceholder | InputPathPlaceholder | OutputPathPlaceholder | ConcatPlaceholderInput | IfPlaceholderInput>;
    /**
     * Else
     */
    else?: Array<string | InputValuePlaceholder | InputPathPlaceholder | OutputPathPlaceholder | ConcatPlaceholderInput | IfPlaceholderInput> | null;
};

/**
 * IfPlaceholderStructure
 */
export type IfPlaceholderStructureOutput = {
    /**
     * Cond
     */
    cond: boolean | string | IsPresentPlaceholder | InputValuePlaceholder;
    /**
     * Then
     */
    then: Array<string | InputValuePlaceholder | InputPathPlaceholder | OutputPathPlaceholder | ConcatPlaceholderOutput | IfPlaceholderOutput>;
    /**
     * Else
     */
    else?: Array<string | InputValuePlaceholder | InputPathPlaceholder | OutputPathPlaceholder | ConcatPlaceholderOutput | IfPlaceholderOutput> | null;
};

/**
 * InputPathPlaceholder
 */
export type InputPathPlaceholder = {
    /**
     * Inputpath
     */
    inputPath: string;
};

/**
 * InputSpec
 */
export type InputSpec = {
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type?: string | {
        [key: string]: unknown;
    } | Array<unknown> | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Default
     */
    default?: string | null;
    /**
     * Optional
     */
    optional?: boolean | null;
    /**
     * Annotations
     */
    annotations?: {
        [key: string]: unknown;
    } | null;
};

/**
 * InputValuePlaceholder
 */
export type InputValuePlaceholder = {
    /**
     * Inputvalue
     */
    inputValue: string;
};

/**
 * IsPresentPlaceholder
 */
export type IsPresentPlaceholder = {
    /**
     * Ispresent
     */
    isPresent: string;
};

/**
 * ListComponentLibrariesResponse
 */
export type ListComponentLibrariesResponse = {
    /**
     * Component Libraries
     */
    component_libraries: Array<ComponentLibraryResponse>;
};

/**
 * ListInstancesResponse
 */
export type ListInstancesResponse = {
    /**
     * Instances
     */
    instances: Array<TangentInstance>;
};

/**
 * ListPipelineJobsResponse
 */
export type ListPipelineJobsResponse = {
    /**
     * Pipeline Runs
     */
    pipeline_runs: Array<PipelineRunResponse>;
    /**
     * Next Page Token
     */
    next_page_token?: string | null;
};

/**
 * ListPublishedComponentsResponse
 */
export type ListPublishedComponentsResponse = {
    /**
     * Published Components
     */
    published_components: Array<PublishedComponentResponse>;
};

/**
 * ListSecretsResponse
 */
export type ListSecretsResponse = {
    /**
     * Secrets
     */
    secrets: Array<SecretInfoResponse>;
};

/**
 * MetadataSpec
 */
export type MetadataSpec = {
    /**
     * Annotations
     */
    annotations?: {
        [key: string]: string;
    } | null;
    /**
     * Labels
     */
    labels?: {
        [key: string]: string;
    } | null;
};

/**
 * OutputPathPlaceholder
 */
export type OutputPathPlaceholder = {
    /**
     * Outputpath
     */
    outputPath: string;
};

/**
 * OutputSpec
 */
export type OutputSpec = {
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type?: string | {
        [key: string]: unknown;
    } | Array<unknown> | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Annotations
     */
    annotations?: {
        [key: string]: unknown;
    } | null;
};

/**
 * PipelineRunResponse
 */
export type PipelineRunResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Root Execution Id
     */
    root_execution_id: string;
    /**
     * Annotations
     */
    annotations?: {
        [key: string]: unknown;
    } | null;
    /**
     * Created By
     */
    created_by?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Pipeline Name
     */
    pipeline_name?: string | null;
    /**
     * Execution Status Stats
     */
    execution_status_stats?: {
        [key: string]: number;
    } | null;
    execution_summary?: ExecutionStatusSummary | null;
};

/**
 * PublishedComponentResponse
 */
export type PublishedComponentResponse = {
    /**
     * Digest
     */
    digest: string;
    /**
     * Published By
     */
    published_by: string;
    /**
     * Deprecated
     */
    deprecated?: boolean;
    /**
     * Superseded By
     */
    superseded_by?: string | null;
    /**
     * Url
     */
    url?: string | null;
    /**
     * Name
     */
    name?: string | null;
};

/**
 * RetryStrategySpec
 */
export type RetryStrategySpec = {
    /**
     * Maxretries
     */
    maxRetries: number;
};

/**
 * SecretInfoResponse
 */
export type SecretInfoResponse = {
    /**
     * Secret Name
     */
    secret_name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Expires At
     */
    expires_at?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * TangentInstance
 */
export type TangentInstance = {
    /**
     * Instance Id
     */
    instance_id: string;
    /**
     * Agent Kinds
     */
    agent_kinds?: Array<string> | null;
};

/**
 * TaskOutputArgument
 */
export type TaskOutputArgument = {
    taskOutput: TaskOutputReference;
};

/**
 * TaskOutputReference
 */
export type TaskOutputReference = {
    /**
     * Outputname
     */
    outputName: string;
    /**
     * Taskid
     */
    taskId: string;
};

/**
 * TaskSpec
 */
export type TaskSpecInput = {
    componentRef: ComponentReferenceInput;
    /**
     * Arguments
     */
    arguments?: {
        [key: string]: string | GraphInputArgument | TaskOutputArgument | DynamicDataArgument;
    } | null;
    /**
     * Isenabled
     */
    isEnabled?: string | GraphInputArgument | TaskOutputArgument | DynamicDataArgument | null;
    executionOptions?: ExecutionOptionsSpec | null;
    /**
     * Annotations
     */
    annotations?: {
        [key: string]: unknown;
    } | null;
};

/**
 * TaskSpec
 */
export type TaskSpecOutput = {
    componentRef: ComponentReferenceOutput;
    /**
     * Arguments
     */
    arguments?: {
        [key: string]: string | GraphInputArgument | TaskOutputArgument | DynamicDataArgument;
    } | null;
    /**
     * Isenabled
     */
    isEnabled?: string | GraphInputArgument | TaskOutputArgument | DynamicDataArgument | null;
    executionOptions?: ExecutionOptionsSpec | null;
    /**
     * Annotations
     */
    annotations?: {
        [key: string]: unknown;
    } | null;
};

/**
 * UserComponentLibraryPinsResponse
 */
export type UserComponentLibraryPinsResponse = {
    /**
     * Component Library Ids
     */
    component_library_ids: Array<string>;
};

/**
 * UserSettingsResponse
 */
export type UserSettingsResponse = {
    /**
     * Settings
     */
    settings: {
        [key: string]: unknown;
    };
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetApiArtifactsIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/artifacts/{id}';
};

export type GetApiArtifactsIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiArtifactsIdGetError = GetApiArtifactsIdGetErrors[keyof GetApiArtifactsIdGetErrors];

export type GetApiArtifactsIdGetResponses = {
    /**
     * Successful Response
     */
    200: GetArtifactInfoResponse;
};

export type GetApiArtifactsIdGetResponse = GetApiArtifactsIdGetResponses[keyof GetApiArtifactsIdGetResponses];

export type GetApiExecutionsIdDetailsGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/executions/{id}/details';
};

export type GetApiExecutionsIdDetailsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiExecutionsIdDetailsGetError = GetApiExecutionsIdDetailsGetErrors[keyof GetApiExecutionsIdDetailsGetErrors];

export type GetApiExecutionsIdDetailsGetResponses = {
    /**
     * Successful Response
     */
    200: GetExecutionInfoResponse;
};

export type GetApiExecutionsIdDetailsGetResponse = GetApiExecutionsIdDetailsGetResponses[keyof GetApiExecutionsIdDetailsGetResponses];

export type GetGraphExecutionStateApiExecutionsIdStateGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/executions/{id}/state';
};

export type GetGraphExecutionStateApiExecutionsIdStateGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGraphExecutionStateApiExecutionsIdStateGetError = GetGraphExecutionStateApiExecutionsIdStateGetErrors[keyof GetGraphExecutionStateApiExecutionsIdStateGetErrors];

export type GetGraphExecutionStateApiExecutionsIdStateGetResponses = {
    /**
     * Successful Response
     */
    200: GetGraphExecutionStateResponse;
};

export type GetGraphExecutionStateApiExecutionsIdStateGetResponse = GetGraphExecutionStateApiExecutionsIdStateGetResponses[keyof GetGraphExecutionStateApiExecutionsIdStateGetResponses];

export type GetGraphExecutionStateApiExecutionsIdGraphExecutionStateGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/executions/{id}/graph_execution_state';
};

export type GetGraphExecutionStateApiExecutionsIdGraphExecutionStateGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGraphExecutionStateApiExecutionsIdGraphExecutionStateGetError = GetGraphExecutionStateApiExecutionsIdGraphExecutionStateGetErrors[keyof GetGraphExecutionStateApiExecutionsIdGraphExecutionStateGetErrors];

export type GetGraphExecutionStateApiExecutionsIdGraphExecutionStateGetResponses = {
    /**
     * Successful Response
     */
    200: GetGraphExecutionStateResponse;
};

export type GetGraphExecutionStateApiExecutionsIdGraphExecutionStateGetResponse = GetGraphExecutionStateApiExecutionsIdGraphExecutionStateGetResponses[keyof GetGraphExecutionStateApiExecutionsIdGraphExecutionStateGetResponses];

export type GetContainerExecutionStateApiExecutionsIdContainerStateGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: {
        /**
         * Include Execution Nodes Linked To Same Container Execution
         */
        include_execution_nodes_linked_to_same_container_execution?: boolean | null;
    };
    url: '/api/executions/{id}/container_state';
};

export type GetContainerExecutionStateApiExecutionsIdContainerStateGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetContainerExecutionStateApiExecutionsIdContainerStateGetError = GetContainerExecutionStateApiExecutionsIdContainerStateGetErrors[keyof GetContainerExecutionStateApiExecutionsIdContainerStateGetErrors];

export type GetContainerExecutionStateApiExecutionsIdContainerStateGetResponses = {
    /**
     * Successful Response
     */
    200: GetContainerExecutionStateResponse;
};

export type GetContainerExecutionStateApiExecutionsIdContainerStateGetResponse = GetContainerExecutionStateApiExecutionsIdContainerStateGetResponses[keyof GetContainerExecutionStateApiExecutionsIdContainerStateGetResponses];

export type GetArtifactsApiExecutionsIdArtifactsGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/executions/{id}/artifacts';
};

export type GetArtifactsApiExecutionsIdArtifactsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetArtifactsApiExecutionsIdArtifactsGetError = GetArtifactsApiExecutionsIdArtifactsGetErrors[keyof GetArtifactsApiExecutionsIdArtifactsGetErrors];

export type GetArtifactsApiExecutionsIdArtifactsGetResponses = {
    /**
     * Successful Response
     */
    200: GetExecutionArtifactsResponse;
};

export type GetArtifactsApiExecutionsIdArtifactsGetResponse = GetArtifactsApiExecutionsIdArtifactsGetResponses[keyof GetArtifactsApiExecutionsIdArtifactsGetResponses];

export type GetContainerLogApiExecutionsIdContainerLogGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/executions/{id}/container_log';
};

export type GetContainerLogApiExecutionsIdContainerLogGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetContainerLogApiExecutionsIdContainerLogGetError = GetContainerLogApiExecutionsIdContainerLogGetErrors[keyof GetContainerLogApiExecutionsIdContainerLogGetErrors];

export type GetContainerLogApiExecutionsIdContainerLogGetResponses = {
    /**
     * Successful Response
     */
    200: GetContainerExecutionLogResponse;
};

export type GetContainerLogApiExecutionsIdContainerLogGetResponse = GetContainerLogApiExecutionsIdContainerLogGetResponses[keyof GetContainerLogApiExecutionsIdContainerLogGetResponses];

export type StreamContainerLogApiExecutionsIdStreamContainerLogGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/executions/{id}/stream_container_log';
};

export type StreamContainerLogApiExecutionsIdStreamContainerLogGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamContainerLogApiExecutionsIdStreamContainerLogGetError = StreamContainerLogApiExecutionsIdStreamContainerLogGetErrors[keyof StreamContainerLogApiExecutionsIdStreamContainerLogGetErrors];

export type StreamContainerLogApiExecutionsIdStreamContainerLogGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListApiPipelineRunsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page Token
         */
        page_token?: string | null;
        /**
         * Filter
         */
        filter?: string | null;
        /**
         * Filter Query
         */
        filter_query?: string | null;
        /**
         * Include Pipeline Names
         */
        include_pipeline_names?: boolean;
        /**
         * Include Execution Stats
         */
        include_execution_stats?: boolean;
    };
    url: '/api/pipeline_runs/';
};

export type ListApiPipelineRunsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListApiPipelineRunsGetError = ListApiPipelineRunsGetErrors[keyof ListApiPipelineRunsGetErrors];

export type ListApiPipelineRunsGetResponses = {
    /**
     * Successful Response
     */
    200: ListPipelineJobsResponse;
};

export type ListApiPipelineRunsGetResponse = ListApiPipelineRunsGetResponses[keyof ListApiPipelineRunsGetResponses];

export type CreateApiPipelineRunsPostData = {
    body: BodyCreateApiPipelineRunsPost;
    path?: never;
    query?: never;
    url: '/api/pipeline_runs/';
};

export type CreateApiPipelineRunsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateApiPipelineRunsPostError = CreateApiPipelineRunsPostErrors[keyof CreateApiPipelineRunsPostErrors];

export type CreateApiPipelineRunsPostResponses = {
    /**
     * Successful Response
     */
    200: PipelineRunResponse;
};

export type CreateApiPipelineRunsPostResponse = CreateApiPipelineRunsPostResponses[keyof CreateApiPipelineRunsPostResponses];

export type GetApiPipelineRunsIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: {
        /**
         * Include Execution Stats
         */
        include_execution_stats?: boolean;
    };
    url: '/api/pipeline_runs/{id}';
};

export type GetApiPipelineRunsIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiPipelineRunsIdGetError = GetApiPipelineRunsIdGetErrors[keyof GetApiPipelineRunsIdGetErrors];

export type GetApiPipelineRunsIdGetResponses = {
    /**
     * Successful Response
     */
    200: PipelineRunResponse;
};

export type GetApiPipelineRunsIdGetResponse = GetApiPipelineRunsIdGetResponses[keyof GetApiPipelineRunsIdGetResponses];

export type GetSignedArtifactUrlApiArtifactsIdSignedArtifactUrlGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/artifacts/{id}/signed_artifact_url';
};

export type GetSignedArtifactUrlApiArtifactsIdSignedArtifactUrlGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSignedArtifactUrlApiArtifactsIdSignedArtifactUrlGetError = GetSignedArtifactUrlApiArtifactsIdSignedArtifactUrlGetErrors[keyof GetSignedArtifactUrlApiArtifactsIdSignedArtifactUrlGetErrors];

export type GetSignedArtifactUrlApiArtifactsIdSignedArtifactUrlGetResponses = {
    /**
     * Successful Response
     */
    200: GetArtifactSignedUrlResponse;
};

export type GetSignedArtifactUrlApiArtifactsIdSignedArtifactUrlGetResponse = GetSignedArtifactUrlApiArtifactsIdSignedArtifactUrlGetResponses[keyof GetSignedArtifactUrlApiArtifactsIdSignedArtifactUrlGetResponses];

export type PipelineRunCancelApiPipelineRunsIdCancelPostData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/pipeline_runs/{id}/cancel';
};

export type PipelineRunCancelApiPipelineRunsIdCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PipelineRunCancelApiPipelineRunsIdCancelPostError = PipelineRunCancelApiPipelineRunsIdCancelPostErrors[keyof PipelineRunCancelApiPipelineRunsIdCancelPostErrors];

export type PipelineRunCancelApiPipelineRunsIdCancelPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListAnnotationsApiPipelineRunsIdAnnotationsGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/pipeline_runs/{id}/annotations/';
};

export type ListAnnotationsApiPipelineRunsIdAnnotationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAnnotationsApiPipelineRunsIdAnnotationsGetError = ListAnnotationsApiPipelineRunsIdAnnotationsGetErrors[keyof ListAnnotationsApiPipelineRunsIdAnnotationsGetErrors];

export type ListAnnotationsApiPipelineRunsIdAnnotationsGetResponses = {
    /**
     * Response List Annotations Api Pipeline Runs  Id  Annotations  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string | null;
    };
};

export type ListAnnotationsApiPipelineRunsIdAnnotationsGetResponse = ListAnnotationsApiPipelineRunsIdAnnotationsGetResponses[keyof ListAnnotationsApiPipelineRunsIdAnnotationsGetResponses];

export type DeleteAnnotationApiPipelineRunsIdAnnotationsKeyDeleteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
        /**
         * Key
         */
        key: string;
    };
    query?: never;
    url: '/api/pipeline_runs/{id}/annotations/{key}';
};

export type DeleteAnnotationApiPipelineRunsIdAnnotationsKeyDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAnnotationApiPipelineRunsIdAnnotationsKeyDeleteError = DeleteAnnotationApiPipelineRunsIdAnnotationsKeyDeleteErrors[keyof DeleteAnnotationApiPipelineRunsIdAnnotationsKeyDeleteErrors];

export type DeleteAnnotationApiPipelineRunsIdAnnotationsKeyDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SetAnnotationApiPipelineRunsIdAnnotationsKeyPutData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
        /**
         * Key
         */
        key: string;
    };
    query?: {
        /**
         * Value
         */
        value?: string | null;
    };
    url: '/api/pipeline_runs/{id}/annotations/{key}';
};

export type SetAnnotationApiPipelineRunsIdAnnotationsKeyPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetAnnotationApiPipelineRunsIdAnnotationsKeyPutError = SetAnnotationApiPipelineRunsIdAnnotationsKeyPutErrors[keyof SetAnnotationApiPipelineRunsIdAnnotationsKeyPutErrors];

export type SetAnnotationApiPipelineRunsIdAnnotationsKeyPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCurrentUserApiUsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type GetCurrentUserApiUsersMeGetResponses = {
    /**
     * Response Get Current User Api Users Me Get
     *
     * Successful Response
     */
    200: GetUserResponse | null;
};

export type GetCurrentUserApiUsersMeGetResponse = GetCurrentUserApiUsersMeGetResponses[keyof GetCurrentUserApiUsersMeGetResponses];

export type ListSecretsApiSecretsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/secrets/';
};

export type ListSecretsApiSecretsGetResponses = {
    /**
     * Successful Response
     */
    200: ListSecretsResponse;
};

export type ListSecretsApiSecretsGetResponse = ListSecretsApiSecretsGetResponses[keyof ListSecretsApiSecretsGetResponses];

export type CreateSecretApiSecretsPostData = {
    body: BodyCreateSecretApiSecretsPost;
    path?: never;
    query: {
        /**
         * Secret Name
         */
        secret_name: string;
        /**
         * Description
         */
        description?: string | null;
        /**
         * Expires At
         */
        expires_at?: string | null;
    };
    url: '/api/secrets/';
};

export type CreateSecretApiSecretsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSecretApiSecretsPostError = CreateSecretApiSecretsPostErrors[keyof CreateSecretApiSecretsPostErrors];

export type CreateSecretApiSecretsPostResponses = {
    /**
     * Successful Response
     */
    200: SecretInfoResponse;
};

export type CreateSecretApiSecretsPostResponse = CreateSecretApiSecretsPostResponses[keyof CreateSecretApiSecretsPostResponses];

export type DeleteSecretApiSecretsSecretNameDeleteData = {
    body?: never;
    path: {
        /**
         * Secret Name
         */
        secret_name: string;
    };
    query?: never;
    url: '/api/secrets/{secret_name}';
};

export type DeleteSecretApiSecretsSecretNameDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSecretApiSecretsSecretNameDeleteError = DeleteSecretApiSecretsSecretNameDeleteErrors[keyof DeleteSecretApiSecretsSecretNameDeleteErrors];

export type DeleteSecretApiSecretsSecretNameDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateSecretApiSecretsSecretNamePutData = {
    body: BodyUpdateSecretApiSecretsSecretNamePut;
    path: {
        /**
         * Secret Name
         */
        secret_name: string;
    };
    query?: {
        /**
         * Description
         */
        description?: string | null;
        /**
         * Expires At
         */
        expires_at?: string | null;
    };
    url: '/api/secrets/{secret_name}';
};

export type UpdateSecretApiSecretsSecretNamePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSecretApiSecretsSecretNamePutError = UpdateSecretApiSecretsSecretNamePutErrors[keyof UpdateSecretApiSecretsSecretNamePutErrors];

export type UpdateSecretApiSecretsSecretNamePutResponses = {
    /**
     * Successful Response
     */
    200: SecretInfoResponse;
};

export type UpdateSecretApiSecretsSecretNamePutResponse = UpdateSecretApiSecretsSecretNamePutResponses[keyof UpdateSecretApiSecretsSecretNamePutResponses];

export type DeleteSettingsApiUsersMeSettingsDeleteData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Setting Names
         */
        setting_names: Array<string>;
    };
    url: '/api/users/me/settings';
};

export type DeleteSettingsApiUsersMeSettingsDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSettingsApiUsersMeSettingsDeleteError = DeleteSettingsApiUsersMeSettingsDeleteErrors[keyof DeleteSettingsApiUsersMeSettingsDeleteErrors];

export type DeleteSettingsApiUsersMeSettingsDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSettingsApiUsersMeSettingsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Setting Names
         */
        setting_names?: Array<string> | null;
    };
    url: '/api/users/me/settings';
};

export type GetSettingsApiUsersMeSettingsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSettingsApiUsersMeSettingsGetError = GetSettingsApiUsersMeSettingsGetErrors[keyof GetSettingsApiUsersMeSettingsGetErrors];

export type GetSettingsApiUsersMeSettingsGetResponses = {
    /**
     * Successful Response
     */
    200: UserSettingsResponse;
};

export type GetSettingsApiUsersMeSettingsGetResponse = GetSettingsApiUsersMeSettingsGetResponses[keyof GetSettingsApiUsersMeSettingsGetResponses];

export type SetSettingsApiUsersMeSettingsPatchData = {
    body: BodySetSettingsApiUsersMeSettingsPatch;
    path?: never;
    query?: never;
    url: '/api/users/me/settings';
};

export type SetSettingsApiUsersMeSettingsPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetSettingsApiUsersMeSettingsPatchError = SetSettingsApiUsersMeSettingsPatchErrors[keyof SetSettingsApiUsersMeSettingsPatchErrors];

export type SetSettingsApiUsersMeSettingsPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetApiComponentsDigestGetData = {
    body?: never;
    path: {
        /**
         * Digest
         */
        digest: string;
    };
    query?: never;
    url: '/api/components/{digest}';
};

export type GetApiComponentsDigestGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiComponentsDigestGetError = GetApiComponentsDigestGetErrors[keyof GetApiComponentsDigestGetErrors];

export type GetApiComponentsDigestGetResponses = {
    /**
     * Successful Response
     */
    200: ComponentResponse;
};

export type GetApiComponentsDigestGetResponse = GetApiComponentsDigestGetResponses[keyof GetApiComponentsDigestGetResponses];

export type ListApiPublishedComponentsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Include Deprecated
         */
        include_deprecated?: boolean;
        /**
         * Name Substring
         */
        name_substring?: string | null;
        /**
         * Published By Substring
         */
        published_by_substring?: string | null;
        /**
         * Digest
         */
        digest?: string | null;
    };
    url: '/api/published_components/';
};

export type ListApiPublishedComponentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListApiPublishedComponentsGetError = ListApiPublishedComponentsGetErrors[keyof ListApiPublishedComponentsGetErrors];

export type ListApiPublishedComponentsGetResponses = {
    /**
     * Successful Response
     */
    200: ListPublishedComponentsResponse;
};

export type ListApiPublishedComponentsGetResponse = ListApiPublishedComponentsGetResponses[keyof ListApiPublishedComponentsGetResponses];

export type PublishApiPublishedComponentsPostData = {
    body: ComponentReferenceInput;
    path?: never;
    query?: never;
    url: '/api/published_components/';
};

export type PublishApiPublishedComponentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublishApiPublishedComponentsPostError = PublishApiPublishedComponentsPostErrors[keyof PublishApiPublishedComponentsPostErrors];

export type PublishApiPublishedComponentsPostResponses = {
    /**
     * Successful Response
     */
    200: PublishedComponentResponse;
};

export type PublishApiPublishedComponentsPostResponse = PublishApiPublishedComponentsPostResponses[keyof PublishApiPublishedComponentsPostResponses];

export type UpdateApiPublishedComponentsDigestPutData = {
    body?: never;
    path: {
        /**
         * Digest
         */
        digest: string;
    };
    query?: {
        /**
         * Deprecated
         */
        deprecated?: boolean | null;
        /**
         * Superseded By
         */
        superseded_by?: string | null;
    };
    url: '/api/published_components/{digest}';
};

export type UpdateApiPublishedComponentsDigestPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateApiPublishedComponentsDigestPutError = UpdateApiPublishedComponentsDigestPutErrors[keyof UpdateApiPublishedComponentsDigestPutErrors];

export type UpdateApiPublishedComponentsDigestPutResponses = {
    /**
     * Successful Response
     */
    200: PublishedComponentResponse;
};

export type UpdateApiPublishedComponentsDigestPutResponse = UpdateApiPublishedComponentsDigestPutResponses[keyof UpdateApiPublishedComponentsDigestPutResponses];

export type ListApiComponentLibrariesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Name Substring
         */
        name_substring?: string | null;
    };
    url: '/api/component_libraries/';
};

export type ListApiComponentLibrariesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListApiComponentLibrariesGetError = ListApiComponentLibrariesGetErrors[keyof ListApiComponentLibrariesGetErrors];

export type ListApiComponentLibrariesGetResponses = {
    /**
     * Successful Response
     */
    200: ListComponentLibrariesResponse;
};

export type ListApiComponentLibrariesGetResponse = ListApiComponentLibrariesGetResponses[keyof ListApiComponentLibrariesGetResponses];

export type CreateApiComponentLibrariesPostData = {
    body: ComponentLibrary;
    path?: never;
    query?: {
        /**
         * Hide From Search
         */
        hide_from_search?: boolean;
    };
    url: '/api/component_libraries/';
};

export type CreateApiComponentLibrariesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateApiComponentLibrariesPostError = CreateApiComponentLibrariesPostErrors[keyof CreateApiComponentLibrariesPostErrors];

export type CreateApiComponentLibrariesPostResponses = {
    /**
     * Successful Response
     */
    200: ComponentLibraryResponse;
};

export type CreateApiComponentLibrariesPostResponse = CreateApiComponentLibrariesPostResponses[keyof CreateApiComponentLibrariesPostResponses];

export type GetApiComponentLibrariesIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: {
        /**
         * Include Component Texts
         */
        include_component_texts?: boolean;
    };
    url: '/api/component_libraries/{id}';
};

export type GetApiComponentLibrariesIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiComponentLibrariesIdGetError = GetApiComponentLibrariesIdGetErrors[keyof GetApiComponentLibrariesIdGetErrors];

export type GetApiComponentLibrariesIdGetResponses = {
    /**
     * Successful Response
     */
    200: ComponentLibraryResponse;
};

export type GetApiComponentLibrariesIdGetResponse = GetApiComponentLibrariesIdGetResponses[keyof GetApiComponentLibrariesIdGetResponses];

export type ReplaceApiComponentLibrariesIdPutData = {
    body: ComponentLibrary;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: {
        /**
         * Hide From Search
         */
        hide_from_search?: boolean | null;
    };
    url: '/api/component_libraries/{id}';
};

export type ReplaceApiComponentLibrariesIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReplaceApiComponentLibrariesIdPutError = ReplaceApiComponentLibrariesIdPutErrors[keyof ReplaceApiComponentLibrariesIdPutErrors];

export type ReplaceApiComponentLibrariesIdPutResponses = {
    /**
     * Successful Response
     */
    200: ComponentLibraryResponse;
};

export type ReplaceApiComponentLibrariesIdPutResponse = ReplaceApiComponentLibrariesIdPutResponses[keyof ReplaceApiComponentLibrariesIdPutResponses];

export type GetComponentLibraryPinsApiComponentLibraryPinsMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/component_library_pins/me/';
};

export type GetComponentLibraryPinsApiComponentLibraryPinsMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserComponentLibraryPinsResponse;
};

export type GetComponentLibraryPinsApiComponentLibraryPinsMeGetResponse = GetComponentLibraryPinsApiComponentLibraryPinsMeGetResponses[keyof GetComponentLibraryPinsApiComponentLibraryPinsMeGetResponses];

export type SetComponentLibraryPinsApiComponentLibraryPinsMePutData = {
    /**
     * Component Library Ids
     */
    body: Array<string>;
    path?: never;
    query?: never;
    url: '/api/component_library_pins/me/';
};

export type SetComponentLibraryPinsApiComponentLibraryPinsMePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetComponentLibraryPinsApiComponentLibraryPinsMePutError = SetComponentLibraryPinsApiComponentLibraryPinsMePutErrors[keyof SetComponentLibraryPinsApiComponentLibraryPinsMePutErrors];

export type SetComponentLibraryPinsApiComponentLibraryPinsMePutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminSetReadOnlyModelApiAdminSetReadOnlyModelPutData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Read Only
         */
        read_only: boolean;
    };
    url: '/api/admin/set_read_only_model';
};

export type AdminSetReadOnlyModelApiAdminSetReadOnlyModelPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminSetReadOnlyModelApiAdminSetReadOnlyModelPutError = AdminSetReadOnlyModelApiAdminSetReadOnlyModelPutErrors[keyof AdminSetReadOnlyModelApiAdminSetReadOnlyModelPutErrors];

export type AdminSetReadOnlyModelApiAdminSetReadOnlyModelPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminSetExecutionNodeStatusApiAdminExecutionNodeIdStatusPutData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query: {
        status: ContainerExecutionStatus;
    };
    url: '/api/admin/execution_node/{id}/status';
};

export type AdminSetExecutionNodeStatusApiAdminExecutionNodeIdStatusPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminSetExecutionNodeStatusApiAdminExecutionNodeIdStatusPutError = AdminSetExecutionNodeStatusApiAdminExecutionNodeIdStatusPutErrors[keyof AdminSetExecutionNodeStatusApiAdminExecutionNodeIdStatusPutErrors];

export type AdminSetExecutionNodeStatusApiAdminExecutionNodeIdStatusPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSqlEngineConnectionPoolStatusApiAdminSqlEngineConnectionPoolStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/sql_engine_connection_pool_status';
};

export type GetSqlEngineConnectionPoolStatusApiAdminSqlEngineConnectionPoolStatusGetResponses = {
    /**
     * Response Get Sql Engine Connection Pool Status Api Admin Sql Engine Connection Pool Status Get
     *
     * Successful Response
     */
    200: string;
};

export type GetSqlEngineConnectionPoolStatusApiAdminSqlEngineConnectionPoolStatusGetResponse = GetSqlEngineConnectionPoolStatusApiAdminSqlEngineConnectionPoolStatusGetResponses[keyof GetSqlEngineConnectionPoolStatusApiAdminSqlEngineConnectionPoolStatusGetResponses];

export type AdminBackfillCreatedByApiAdminBackfillCreatedByPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/backfill/created_by';
};

export type AdminBackfillCreatedByApiAdminBackfillCreatedByPostResponses = {
    /**
     * Response Admin Backfill Created By Api Admin Backfill Created By Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AdminBackfillCreatedByApiAdminBackfillCreatedByPostResponse = AdminBackfillCreatedByApiAdminBackfillCreatedByPostResponses[keyof AdminBackfillCreatedByApiAdminBackfillCreatedByPostResponses];

export type AdminBackfillPipelineNamesExtraDataApiAdminBackfillPipelineNamesExtraDataPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/backfill/pipeline_names/extra_data';
};

export type AdminBackfillPipelineNamesExtraDataApiAdminBackfillPipelineNamesExtraDataPostResponses = {
    /**
     * Response Admin Backfill Pipeline Names Extra Data Api Admin Backfill Pipeline Names Extra Data Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AdminBackfillPipelineNamesExtraDataApiAdminBackfillPipelineNamesExtraDataPostResponse = AdminBackfillPipelineNamesExtraDataApiAdminBackfillPipelineNamesExtraDataPostResponses[keyof AdminBackfillPipelineNamesExtraDataApiAdminBackfillPipelineNamesExtraDataPostResponses];

export type AdminBackfillPipelineNamesComponentSpecApiAdminBackfillPipelineNamesComponentSpecPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/backfill/pipeline_names/component_spec';
};

export type AdminBackfillPipelineNamesComponentSpecApiAdminBackfillPipelineNamesComponentSpecPostResponses = {
    /**
     * Response Admin Backfill Pipeline Names Component Spec Api Admin Backfill Pipeline Names Component Spec Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AdminBackfillPipelineNamesComponentSpecApiAdminBackfillPipelineNamesComponentSpecPostResponse = AdminBackfillPipelineNamesComponentSpecApiAdminBackfillPipelineNamesComponentSpecPostResponses[keyof AdminBackfillPipelineNamesComponentSpecApiAdminBackfillPipelineNamesComponentSpecPostResponses];

export type AdminBackfillAllApiAdminBackfillAllPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/backfill/all';
};

export type AdminBackfillAllApiAdminBackfillAllPostResponses = {
    /**
     * Response Admin Backfill All Api Admin Backfill All Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AdminBackfillAllApiAdminBackfillAllPostResponse = AdminBackfillAllApiAdminBackfillAllPostResponses[keyof AdminBackfillAllApiAdminBackfillAllPostResponses];

export type FlagStatsApiStatsFlagsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Format
         *
         * Response format: 'html' or 'json'
         */
        format?: string;
    };
    url: '/api/stats/flags';
};

export type FlagStatsApiStatsFlagsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FlagStatsApiStatsFlagsGetError = FlagStatsApiStatsFlagsGetErrors[keyof FlagStatsApiStatsFlagsGetErrors];

export type FlagStatsApiStatsFlagsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PingServicesPingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/services/ping';
};

export type PingServicesPingGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type QuickStatsApiStatsQuickGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Format
         *
         * Response format: 'html' or 'json'
         */
        format?: string;
    };
    url: '/api/stats/quick';
};

export type QuickStatsApiStatsQuickGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type QuickStatsApiStatsQuickGetError = QuickStatsApiStatsQuickGetErrors[keyof QuickStatsApiStatsQuickGetErrors];

export type QuickStatsApiStatsQuickGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProxyApiTangentInstancesInstanceIdOpencodeApiPathDeleteData = {
    body?: never;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/api/tangent/instances/{instance_id}/opencode/api/{path}';
};

export type ProxyApiTangentInstancesInstanceIdOpencodeApiPathDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProxyApiTangentInstancesInstanceIdOpencodeApiPathDeleteError = ProxyApiTangentInstancesInstanceIdOpencodeApiPathDeleteErrors[keyof ProxyApiTangentInstancesInstanceIdOpencodeApiPathDeleteErrors];

export type ProxyApiTangentInstancesInstanceIdOpencodeApiPathDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProxyApiTangentInstancesInstanceIdOpencodeApiPathGetData = {
    body?: never;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/api/tangent/instances/{instance_id}/opencode/api/{path}';
};

export type ProxyApiTangentInstancesInstanceIdOpencodeApiPathGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProxyApiTangentInstancesInstanceIdOpencodeApiPathGetError = ProxyApiTangentInstancesInstanceIdOpencodeApiPathGetErrors[keyof ProxyApiTangentInstancesInstanceIdOpencodeApiPathGetErrors];

export type ProxyApiTangentInstancesInstanceIdOpencodeApiPathGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProxyApiTangentInstancesInstanceIdOpencodeApiPathPatchData = {
    body?: never;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/api/tangent/instances/{instance_id}/opencode/api/{path}';
};

export type ProxyApiTangentInstancesInstanceIdOpencodeApiPathPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProxyApiTangentInstancesInstanceIdOpencodeApiPathPatchError = ProxyApiTangentInstancesInstanceIdOpencodeApiPathPatchErrors[keyof ProxyApiTangentInstancesInstanceIdOpencodeApiPathPatchErrors];

export type ProxyApiTangentInstancesInstanceIdOpencodeApiPathPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProxyApiTangentInstancesInstanceIdOpencodeApiPathPostData = {
    body?: never;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/api/tangent/instances/{instance_id}/opencode/api/{path}';
};

export type ProxyApiTangentInstancesInstanceIdOpencodeApiPathPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProxyApiTangentInstancesInstanceIdOpencodeApiPathPostError = ProxyApiTangentInstancesInstanceIdOpencodeApiPathPostErrors[keyof ProxyApiTangentInstancesInstanceIdOpencodeApiPathPostErrors];

export type ProxyApiTangentInstancesInstanceIdOpencodeApiPathPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProxyApiTangentInstancesInstanceIdOpencodeApiPathPutData = {
    body?: never;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/api/tangent/instances/{instance_id}/opencode/api/{path}';
};

export type ProxyApiTangentInstancesInstanceIdOpencodeApiPathPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProxyApiTangentInstancesInstanceIdOpencodeApiPathPutError = ProxyApiTangentInstancesInstanceIdOpencodeApiPathPutErrors[keyof ProxyApiTangentInstancesInstanceIdOpencodeApiPathPutErrors];

export type ProxyApiTangentInstancesInstanceIdOpencodeApiPathPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListInstancesApiTangentInstancesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tangent/instances';
};

export type ListInstancesApiTangentInstancesGetResponses = {
    /**
     * Successful Response
     */
    200: ListInstancesResponse;
};

export type ListInstancesApiTangentInstancesGetResponse = ListInstancesApiTangentInstancesGetResponses[keyof ListInstancesApiTangentInstancesGetResponses];

export type CreateInstanceApiTangentInstancesPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tangent/instances';
};

export type CreateInstanceApiTangentInstancesPostResponses = {
    /**
     * Successful Response
     */
    200: TangentInstance;
};

export type CreateInstanceApiTangentInstancesPostResponse = CreateInstanceApiTangentInstancesPostResponses[keyof CreateInstanceApiTangentInstancesPostResponses];

export type RedirectToDefaultInstanceApiTangentGoGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tangent/go';
};

export type RedirectToDefaultInstanceApiTangentGoGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
